---

# Install the AWS CLI v2.
- name: Include AWS CLI
  include_tasks:
    file: awscli/main.yml
    apply:
      tags: aws-cli
  tags:
    - aws-cli
  when: ansible_os_family != 'Windows'

# Install the AWS SSM Agent.
- name: Include AWS SSM Agent
  include_tasks:
    file: ssm-agent/main.yml
    apply:
      tags: aws-ssm
  tags:
    - aws-ssm

# Install the AWS Copilot CLI.
- name: Include AWS Copilot CLI
  include_tasks:
    file: copilot-cli/main.yml
    apply:
      tags: copilot-cli
  tags:
    - copilot-cli
