---

- name: Install NVIDIA Dependencies
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - libglvnd-glx
    - libglvnd-opengl
    - libglvnd-devel
    - vulkan
    - "kernel-devel-{{ ansible_kernel }}"
    - "kernel-headers-{{ ansible_kernel }}"
  become: true
  register: nvidia_dependencies

- name: Reboot
  reboot:
    reboot_timeout: 1800
  become: true
  when: nvidia_dependencies.changed

- name: Verify whether NVIDIA Drivers are installed
  command: nvidia-smi
  register: nvidia_smi
  changed_when: false
  failed_when: false

- name: Save whether NVIDIA Drivers are installed
  set_fact:
    nvidia_driver_installed: "{{ True if nvidia_smi.rc == 0 else False }}"

# NVIDIA Drivers Installation Block.
- block:

  - name: Create a local temporary directory
    tempfile:
      state: directory
      suffix: drivers
    register: nvidia_local_drivers_directory
    run_once: true
    delegate_to: localhost

  - name: List NVIDIA Drivers
    amazon.aws.aws_s3:
      bucket: "{{ nvidia_bucket }}"
      prefix : "{{ nvidia_bucket_prefix }}"
      mode: list
    delegate_to: localhost
    run_once: true
    register: nvidia_drivers_bucket_keys

  - name: Download NVIDIA Drivers
    amazon.aws.s3_object:
      bucket: "{{ nvidia_bucket }}"
      object: "{{ nvidia_drivers_bucket_keys.s3_keys[0] }}"
      dest: "{{ [nvidia_local_drivers_directory.path, nvidia_install_file] | path_join }}"
      region: "{{ nvidia_bucket_region }}"
      mode: get
    delegate_to: localhost
    run_once: true

  - name: Upload NVIDIA Drivers
    copy:
      src: "{{ [nvidia_local_drivers_directory.path, nvidia_install_file] | path_join }}"
      dest: "{{ ansible_user_dir }}"
      mode: 0700

  - name: Install NVIDIA Drivers
    command:
      cmd: "{{ [ansible_user_dir, nvidia_install_file] | path_join }} --dkms --silent"
    register: nvidia_drivers
    become: true

  - name: Reboot
    reboot:
      reboot_timeout: 1800
    become: true
    when: nvidia_drivers.changed
  
  when: not nvidia_driver_installed

- name: Create xorg.conf file
  command: >
    nvidia-xconfig
      --enable-all-gpus
      --allow-empty-initial-configuration
      --virtual={{ baseline_resolution }}
  become: true
  notify:
    - xorg_conf_changed

- name: Flush handlers
  meta: flush_handlers
