---

- name: Install NVIDIA Dependencies
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - build-essential
    - libc-dev
    - libc6-dev
    - libvulkan1
    - libglvnd-dev
    - "linux-headers-{{ ansible_kernel }}"
  become: true

- name: Download CUDA Keyring
  get_url:
    url: "{{ nvidia_keyring_url }}"
    dest: /tmp/cuda-keyring.deb

- name: Install CUDA Keyring
  apt:
    deb: /tmp/cuda-keyring.deb
    state: present
  become: true

- name: Install NVIDIA Drivers
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - cuda-drivers
    - nvtop
    - libglu1-mesa
  become: true
  async: 900
  poll: 10
  register: install_nvidia_drivers

- name: Install libegl1-mesa (Ubuntu <24.04)
  apt:
    name: libegl1-mesa
  become: true
  when: ansible_distribution_version < '24.04'

- name: Install libegl1-mesa (Ubuntu >=24.04)
  apt:
    name: libegl1-mesa-dev
  become: true
  when: ansible_distribution_version >= '24.04'

- name: Reboot
  reboot:
    reboot_timeout: 1800
  become: true
  when: install_nvidia_drivers.changed

- name: Create xorg.conf file
  command: >
    nvidia-xconfig
      --enable-all-gpus
      --allow-empty-initial-configuration
      --virtual={{ baseline_resolution }}
  become: true
  notify:
    - xorg_conf_changed

- name: Flush handlers
  meta: flush_handlers
