---

# This section will download the NVIDIA GRID drivers locally from an AWS
# managed S3 bucket, the deployment machine must have valid AWS credentials
# and have the botocore and boto3 libraries installed to download the drivers.
 
- name: Create a local temporary directory
  tempfile:
    state: directory
    suffix: drivers
  register: local_drivers_directory
  run_once: true
  delegate_to: localhost

- name: Download NVIDIA Drivers
  amazon.aws.s3_object:
    bucket: "{{ nvidia_bucket }}"
    object: "{{ nvidia_object }}"
    dest: "{{ [local_drivers_directory.path, nvidia_install_file] | path_join }}"
    mode: get
  delegate_to: localhost
  run_once: true

- name: Upload NVIDIA Drivers
  win_copy:
    src: "{{ [local_drivers_directory.path, nvidia_install_file] | path_join }}"
    dest: "{{ ansible_user_dir }}"
  register: driver_upload

- name: Install NVIDIA Drivers
  win_package:
    path: "{{ [ansible_user_dir, nvidia_install_file] | path_join }}"
    arguments:
      # Silent installation.
      - "-s"
      # No reboot.
      - "-n"
  register: install_nvidia_drivers

- name: Reboot
  win_reboot:
    reboot_timeout: 1800
  when: install_nvidia_drivers.changed
