---

# Add Fedora EPEL package to access DKMS specific version
# allowing to install AMD GPU drivers.
- name: Install EPEL package
  package:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present
    update_cache: true
    disable_gpg_check: true
  become: true

# Add EPEL package to the distribution
# to access extended packages.
- name: Install EPEL package
  command:
    cmd: amazon-linux-extras install epel -y
  become: true
  args:
    creates: /etc/yum.repos.d/epel.repo

- name: Install Core Packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ package_prerequisites }}"
  become: true
