---

# Install dependencies.
- name: Install EFS Helper Dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rpm-build
    - stunnel
  become: true

# Clone repository.
- name: Clone EFS Helper
  git:
    repo: 'https://github.com/aws/efs-utils'
    dest: /tmp/efs-utils

# Build packages.
- name: Build EFS Helper Packages
  command:
    cmd: make rpm
    chdir: /tmp/efs-utils/
  args:
    creates: /tmp/efs-utils/build

# List packages.
- name: List EFS Helper Packages
  find:
    path: /tmp/efs-utils/build
    patterns: 'amazon-efs-utils*rpm'
  register: efs_helper_packages

# Install.
- name: Install EFS Helper
  yum:
    name: '{{ item.path }}'
    disable_gpg_check: true
  with_items: '{{ efs_helper_packages.files }}'
  become: true
