---

- name: Install AWS Copilot CLI
  shell: >
    curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux \
      && chmod +x copilot \
      && sudo mv copilot /usr/local/bin/copilot
  become: true
  args:
    creates: /usr/local/bin/copilot
