---

- name: Install Kitty and ZSH
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - zsh
    - kitty
  become: true

- name: Create Kitty configuration directory
  file:
    path: '{{ ansible_user_dir }}/.config/kitty'
    state: directory
    mode: 0755

- name: Copy the Kitty configuration file
  copy:
    src: files/kitty.conf
    dest: '{{ ansible_user_dir }}/.config/kitty/kitty.conf'
    mode: 0755
