---

- name: Add Repositories
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck }}"
  with_items: "{{ repositories }}"
  become: true

- name: Start snapd
  service:
    name: snapd
    state: started
    enabled: true
  become: true

- name: Verify whether the snapd directory exists
  stat:
    path: /snap
  become: true
  register: snap_link

- name: Create snapd symlink
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  when: not snap_link.stat.exists
  become: true

- name: Add Flatpak Repositories
  flatpak_remote:
    name: "{{ item.name }}"
    flatpakrepo_url: "{{ item.repo }}"
    state: present
  with_items: "{{ flatpak_repositories }}"
  become: true

- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
    use: dnf
  with_items: "{{ native_packages }}"
  become: true

- name: Install Snaps
  snap:
    name: "{{ item }}"
    classic: true
  with_items: "{{ snaps_to_install }}"
  become: true

- name: Install Flatpaks
  flatpak:
    name: "{{ item }}"
  with_items: "{{ flatpak_packages }}"
  become: true

- name: Install Pip Packages
  pip:
    name: "{{ item }}"
  with_items: "{{ pip_packages }}"
